### ISSUE TITLE
Tabs become taller when hovering, UI jumps

### ISSUE THREAD

**Issue by Bilka2** [wilfredwee/photon-australis#6]
FF57, dark theme. When I hover over tabs the entire row of tabs is taller than normal. Could not fix it by removing the height properties from the hover stuff.

**Comment by wilfredwee** [comment]
Hi, can you provide me with your OS and screen resolution? Are you using userChrome-dark.css with the Dark Theme?

Having reproduction steps and maybe a video/gif would help as well.

**Comment by Bilka2** [comment]
Windows 10 (no creators update installed), 1080p. I'm just using userChrome.css, pasting the code into userChrome-dark.css does nothing (it does not apply). Here is a gif of what's happening: https://gfycat.com/SingleFirmAntlion

Another thing: The two most left tabs are pinned, the space left of them seems a bit too big.

**Comment by wilfredwee** [comment]
Interesting, I'll see if I can reproduce it over the weekend.

The space on the left is a potential enhancement.

**Comment by ErroneousBee** [comment]
Ive added a margin-top to one of the tab:hover rules, seems to have fixed it for me on the default theme:

```css
#TabsToolbar[brighttext] > #tabbrowser-tabs > .tabbrowser-tab:hover > .tab-stack > .tab-background:not([selected="true"]),
.tabs-newtab-button:hover,
.tabs-newtab-button:hover::before,
.tabs-newtab-button:hover::after {
  background-color: transparent !important;
  margin-top: 0px !important;
}
```
